import Head from 'next/head'
import Header from '@/components/Header'
import classes from '@/styles/index.module.css'
import LinkButton from '@/components/LinkButton'
import TabGroup from '@/components/TabGroup'

export default function Home() {
  return (
    <>
      <Head>
        <title>C-Qustionare(トップページ)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={classes.mask}>
        <div className={classes.visual_box}>
          <img src="" alt="" />
          <LinkButton link="#" text="C-questionareについて" isAbsolute={true}/>
        </div>
        <main className={classes.main_container}>
          <TabGroup />
        </main>
      </div>
    </>
  )
}
